<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.fincons.pgd</groupId>
	<artifactId>parent</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>PGDDemo parent</name>
	<packaging>pom</packaging>
	<description/>
	<url/>

	<licenses>
		<license/>
	</licenses>

	<developers>
		<developer/>
	</developers>

	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>

	<properties>
		<java.version>21</java.version>
		<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>
		<character.encoding>UTF-8</character.encoding>
		<project.build.sourceEncoding>${character.encoding}</project.build.sourceEncoding>
		<project.reporting.outputEncoding>${character.encoding}</project.reporting.outputEncoding>
		<spring-boot.version>4.0.5</spring-boot.version>
	</properties>

	<modules>
		<module>PGDDemo</module>
<!--		<module>amministrazione</module>-->
<!--		<module>batch-operation-async</module>-->
<!--		<module>comuni</module>-->
<!--		<module>documenti</module>-->
<!--		<module>reportistica</module>-->
<!--		<module>spesadelega</module>-->
		<module>utenti</module>
<!--		<module>validita-delega</module>-->
<!--		<module>lib-security</module>-->
<!--		<module>lib-utility</module>-->
	</modules>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>2.0.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.projectreactor</groupId>
                <artifactId>reactor-bom</artifactId>
                <version>2025.0.0-RC1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

		</dependencies>
	</dependencyManagement>
</project>
