spring.application.name=PGDDemo


logging.level.root=info
logging.level.com.fincons=debug

logging.file.name=./PGDDemo.log
logging.pattern.console=  %d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\\(%F:%L\\) - %msg%n


server.port = 9070

spring.datasource.url=jdbc:postgresql://psql-pgddemo-2026.postgres.database.azure.com:5432/PGDDemo?sslmode=require
spring.datasource.username=pgdadmin
spring.datasource.password=D0r1c0nnect!
#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/PGDDemo
#spring.datasource.username=postgres
#spring.datasource.password=admin


spring.jpa.show-sql= false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=define.sql
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=drop.sql
spring.jpa.properties.hibernate.hbm2ddl.schema-generation.script.append=false

spring.security.user.name=user
spring.security.user.password=pwd

lang=IT

app.upload.dir=uploads

# Ollama
spring.ai.ollama.base-url=http://host.docker.internal:11434
#spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen3:4b
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

# Alibaba DashScope
spring.ai.dashscope.api-key=${AI_DASHSCOPE_API_KEY}
spring.ai.dashscope.base-url=https://ws-srfsnb5ae48l2xey.ap-southeast-1.maas.aliyuncs.com
spring.ai.dashscope.chat.options.model=qwen3.7-plus
spring.ai.dashscope.chat.options.temperature=0.7
spring.ai.dashscope.chat.options.multi-model=true

spring.autoconfigure.exclude=com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeMultimodalEmbeddingAutoConfiguration

git.repository.path=/app/repository

spring.devtools.restart.enabled=false

management.endpoints.web.exposure.include=health,info

springdoc.show-actuator=true