
    create table appuntamento (
        data_creazione_appuntamento timestamp(6),
        id bigint generated by default as identity,
        id_delegante_fk bigint,
        id_delegato_fk bigint,
        primary key (id)
    );

    create table associativautenteprofilo (
        flag_abilitazione boolean,
        data_abilitazione timestamp(6),
        id bigint generated by default as identity,
        id_operatore_fk bigint,
        id_profilo_fk bigint,
        id_utente_fk bigint,
        primary key (id)
    );

    create table delega (
        data_fine_validita date,
        data_inizio_validita date,
        dic_esercente_resp_genitoriale_approvatore boolean,
        dic_esercente_resp_genitoriale_delegato boolean,
        flag_responsabilita_genitoriale boolean,
        data_creazione timestamp(6),
        data_ultimo_aggiornamento timestamp(6),
        data_video_registrazione timestamp(6),
        id bigint generated by default as identity,
        id_operatore bigint,
        id_scenario_fk bigint,
        id_tipo_delegato_fk bigint not null,
        id_ultimo_stato_delega bigint not null,
        id_utente_delegante_fk bigint,
        id_utente_delegato_fk bigint,
        codice_univoco_delega varchar(255) unique,
        esito_verifica_responsabilita_genitoriale varchar(255),
        id_video_chiamata varchar(255),
        primary key (id)
    );

    create table documentiallegati (
        data_caricamento timestamp(6) not null,
        id bigint generated by default as identity,
        id_delega_fk bigint not null,
        id_tipologia_documento_fk bigint not null,
        formato_file varchar(10),
        nome_file varchar(255) not null unique,
        path_bucket varchar(255),
        primary key (id)
    );

    create table logproxy (
        status_code integer,
        data_chiamata timestamp(6) not null,
        data_risposta timestamp(6),
        id bigint generated by default as identity,
        id_delega_fk bigint,
        dati_input TEXT,
        dati_output TEXT,
        eccezione TEXT,
        servizio_chiamato varchar(255),
        severity varchar(255) check ((severity in ('INFO','WARNING','ERROR','FATAL'))),
        primary key (id)
    );

    create table messaggi_sistema (
        lang varchar(4) not null,
        code varchar(20) not null,
        messaggio varchar(255),
        primary key (lang, code)
    );

    create table operatore (
        id bigint generated by default as identity,
        codice_univoco varchar(255) not null unique,
        primary key (id)
    );

    create table profilo (
        id bigint generated by default as identity,
        descrizione varchar(255),
        gruppi_active_directory varchar(255),
        nome_profilo varchar(255) not null unique,
        primary key (id)
    );

    create table scenario (
        flag_attivo boolean,
        id bigint generated by default as identity,
        descrizione TEXT,
        label_scenario varchar(255),
        nome varchar(255) not null,
        primary key (id)
    );

    create table statoappuntamento (
        id bigint generated by default as identity,
        nome_stato varchar(100) not null unique,
        descrizione_stato varchar(500),
        primary key (id)
    );

    create table statodelega (
        id bigint generated by default as identity,
        descrizione_stato varchar(255),
        nome_stato varchar(255) not null unique,
        primary key (id)
    );

    create table storicodelega (
        data_cambio_stato timestamp(6) not null,
        id bigint generated by default as identity,
        id_delega_fk bigint not null,
        id_stato_delega_fk bigint not null,
        id_utente_cambio_stato_fk bigint,
        causa varchar(500),
        primary key (id)
    );

    create table storicostatoappuntamento (
        data_cambio_stato timestamp(6) not null,
        id bigint generated by default as identity,
        id_appuntamento_fk bigint not null,
        id_stato_appuntamento_fk bigint not null,
        id_utente_cambio_stato_fk bigint,
        primary key (id)
    );

    create table tipodelegato (
        id bigint generated by default as identity,
        descrizione varchar(255),
        nome varchar(255) not null unique,
        primary key (id)
    );

    create table tipologiadocumento (
        id bigint generated by default as identity,
        formati_ammessi varchar(255),
        nome_file varchar(255),
        nome_modello varchar(255) not null,
        path_bucket varchar(255),
        primary key (id)
    );

    create table utente (
        data_nascita date not null,
        flag_accettazione_policy boolean,
        flag_email_certificata boolean,
        id bigint generated by default as identity,
        codice_fiscale varchar(16) not null unique,
        cognome varchar(255) not null,
        idpnr varchar(255) not null unique,
        indirizzo_email varchar(255) not null,
        luogo_di_nascita varchar(255) not null,
        nome varchar(255) not null,
        residenza varchar(255) not null,
        primary key (id)
    );

    alter table if exists appuntamento 
       add constraint FKw0v0mkrxb4oamr38xm51imtv 
       foreign key (id_delegante_fk) 
       references utente;

    alter table if exists appuntamento 
       add constraint FKalxcwgpdmivy7p7llwvyaemgc 
       foreign key (id_delegato_fk) 
       references utente;

    alter table if exists associativautenteprofilo 
       add constraint FKixjc37a3d0jhsob759gqih1bn 
       foreign key (id_operatore_fk) 
       references operatore;

    alter table if exists associativautenteprofilo 
       add constraint FKlk1oaftqb8jugv2rmiglabamp 
       foreign key (id_profilo_fk) 
       references profilo;

    alter table if exists associativautenteprofilo 
       add constraint FK7vubn1vyoas8mtjw9ofv28le6 
       foreign key (id_utente_fk) 
       references utente;

    alter table if exists delega 
       add constraint FK245vyld9ifjaw353ojn9yn1sg 
       foreign key (id_operatore) 
       references operatore;

    alter table if exists delega 
       add constraint FK1mmeaobkuv245chn7shhb5ih1 
       foreign key (id_scenario_fk) 
       references scenario;

    alter table if exists delega 
       add constraint FKtkjovr2le9oyq0qf5c71v2j0i 
       foreign key (id_ultimo_stato_delega) 
       references statodelega;

    alter table if exists delega 
       add constraint FK6q3qpa03d5sxefenaubo8gljd 
       foreign key (id_tipo_delegato_fk) 
       references tipodelegato;

    alter table if exists delega 
       add constraint FKcrflwniqlgnkl0dp0fx978j6k 
       foreign key (id_utente_delegante_fk) 
       references utente;

    alter table if exists delega 
       add constraint FK73olidakub711s9184wopu2f2 
       foreign key (id_utente_delegato_fk) 
       references utente;

    alter table if exists documentiallegati 
       add constraint FK8us5dkm6nbhxm7isa2uuckcrq 
       foreign key (id_delega_fk) 
       references delega;

    alter table if exists documentiallegati 
       add constraint FK8ges02h5rql6919vvspvlubw2 
       foreign key (id_tipologia_documento_fk) 
       references tipologiadocumento;

    alter table if exists logproxy 
       add constraint FKd4yfr967dni97n89p3t9opkmx 
       foreign key (id_delega_fk) 
       references delega;

    alter table if exists storicodelega 
       add constraint FK67ity6goblm8ljes857uvxv0n 
       foreign key (id_delega_fk) 
       references delega;

    alter table if exists storicodelega 
       add constraint FK8ms0lq591ijw4mykqo7ldh1j1 
       foreign key (id_stato_delega_fk) 
       references statodelega;

    alter table if exists storicodelega 
       add constraint FK70hhpmfcvaa21k0xy4wbw87pu 
       foreign key (id_utente_cambio_stato_fk) 
       references utente;

    alter table if exists storicostatoappuntamento 
       add constraint FKkjktlcopfy328futpx56s7qf0 
       foreign key (id_appuntamento_fk) 
       references appuntamento;

    alter table if exists storicostatoappuntamento 
       add constraint FKb772eke5pg8vp6ri976392ye9 
       foreign key (id_stato_appuntamento_fk) 
       references statoappuntamento;

    alter table if exists storicostatoappuntamento 
       add constraint FKjbxxcyy354ves2htqdqou22sl 
       foreign key (id_utente_cambio_stato_fk) 
       references utente;
