
    create table appuntamento (
        data_creazione_appuntamento timestamp(6),
        id bigint generated by default as identity,
        id_delegante_fk bigint,
        id_delegato_fk bigint,
        primary key (id)
    );

    create table associativautenteprofilo (
        flag_abilitazione boolean,
        data_abilitazione timestamp(6),
        id bigint generated by default as identity,
        id_profilo_fk bigint,
        id_utente_fk bigint,
        primary key (id)
    );

    create table delega (
        data_fine_validita date,
        data_inizio_validita date,
        id bigint generated by default as identity,
        id_scenario_fk bigint,
        id_utente_delegante_fk bigint,
        id_utente_delegato_fk bigint,
        codice_univoco_delega varchar(255) unique,
        primary key (id)
    );

    create table profilo (
        id bigint generated by default as identity,
        descrizione varchar(255),
        gruppi_active_directory varchar(255),
        nome_profilo varchar(255) not null unique,
        primary key (id)
    );

    create table scenario (
        flag_attivo boolean,
        id bigint generated by default as identity,
        descrizione TEXT,
        label_scenario varchar(255),
        nome varchar(255) not null,
        primary key (id)
    );

    create table statoappuntamento (
        id bigint generated by default as identity,
        nome_stato varchar(100) not null unique,
        descrizione_stato varchar(500),
        primary key (id)
    );

    create table statodelega (
        id bigint generated by default as identity,
        descrizione_stato varchar(255),
        nome_stato varchar(255) not null unique,
        primary key (id)
    );

    create table storicodelega (
        data_cambio_stato timestamp(6) not null,
        id bigint generated by default as identity,
        id_delega_fk bigint not null,
        id_stato_delega_fk bigint not null,
        id_utente_cambio_stato_fk bigint,
        causa varchar(500),
        primary key (id)
    );

    create table storicostatoappuntamento (
        data_cambio_stato timestamp(6) not null,
        id bigint generated by default as identity,
        id_appuntamento_fk bigint not null,
        id_stato_appuntamento_fk bigint not null,
        id_utente_cambio_stato_fk bigint,
        primary key (id)
    );

    create table utente (
        flag_accettazione_proxy boolean,
        flag_email_certificata boolean,
        id bigint generated by default as identity,
        codice_fiscale varchar(255),
        cognome varchar(255),
        indirizzo_email varchar(255),
        nome varchar(255),
        primary key (id)
    );

    alter table if exists appuntamento 
       add constraint FKw0v0mkrxb4oamr38xm51imtv 
       foreign key (id_delegante_fk) 
       references utente;

    alter table if exists appuntamento 
       add constraint FKalxcwgpdmivy7p7llwvyaemgc 
       foreign key (id_delegato_fk) 
       references utente;

    alter table if exists associativautenteprofilo 
       add constraint FKlk1oaftqb8jugv2rmiglabamp 
       foreign key (id_profilo_fk) 
       references profilo;

    alter table if exists associativautenteprofilo 
       add constraint FK7vubn1vyoas8mtjw9ofv28le6 
       foreign key (id_utente_fk) 
       references utente;

    alter table if exists delega 
       add constraint FK1mmeaobkuv245chn7shhb5ih1 
       foreign key (id_scenario_fk) 
       references scenario;

    alter table if exists delega 
       add constraint FKcrflwniqlgnkl0dp0fx978j6k 
       foreign key (id_utente_delegante_fk) 
       references utente;

    alter table if exists delega 
       add constraint FK73olidakub711s9184wopu2f2 
       foreign key (id_utente_delegato_fk) 
       references utente;

    alter table if exists storicodelega 
       add constraint FK67ity6goblm8ljes857uvxv0n 
       foreign key (id_delega_fk) 
       references delega;

    alter table if exists storicodelega 
       add constraint FK8ms0lq591ijw4mykqo7ldh1j1 
       foreign key (id_stato_delega_fk) 
       references statodelega;

    alter table if exists storicodelega 
       add constraint FK70hhpmfcvaa21k0xy4wbw87pu 
       foreign key (id_utente_cambio_stato_fk) 
       references utente;

    alter table if exists storicostatoappuntamento 
       add constraint FKkjktlcopfy328futpx56s7qf0 
       foreign key (id_appuntamento_fk) 
       references appuntamento;

    alter table if exists storicostatoappuntamento 
       add constraint FKb772eke5pg8vp6ri976392ye9 
       foreign key (id_stato_appuntamento_fk) 
       references statoappuntamento;

    alter table if exists storicostatoappuntamento 
       add constraint FKjbxxcyy354ves2htqdqou22sl 
       foreign key (id_utente_cambio_stato_fk) 
       references utente;
